# Generated by Django 2.0.1 on 2018-12-11 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('added_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
