# Generated by Django 2.0.1 on 2018-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181211_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='lastname',
        ),
        migrations.AddField(
            model_name='accounts',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
