# Generated by Django 2.0.1 on 2018-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181211_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
