# Generated by Django 2.0.1 on 2018-12-17 04:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
                ('Binan', django.db.models.manager.Manager()),
            ],
        ),
    ]
