# Generated by Django 2.0.1 on 2018-12-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181217_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user',
            new_name='userprofile',
        ),
    ]
